In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("customer_segmentation_mixed.csv")

In [4]:
df

,Age,Annual_Income,Spending_Score,Monthly_Visits,Gender,Preferred_Product
0,56,26102,85,6,Female,Clothing
1,46,70336,75,18,Male,Home
2,32,105314,36,10,Male,Groceries
3,60,46641,99,5,Female,Electronics
4,25,54584,19,10,Male,Electronics
...,...,...,...,...,...,...
345,48,87641,37,12,Female,Home
346,52,56395,11,12,Male,Home
347,50,42700,77,19,Male,Clothing
348,38,54620,3,6,Female,Electronics
349,49,40559,33,2,Male,Clothing

In [1]:
import seaborn as sns

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
li=LabelEncoder()

In [10]:
col=['Gender','Preferred_Product']

In [18]:
for i in col: 
    df[i]=li.fit_transform(df[i])

In [12]:
df

,Age,Annual_Income,Spending_Score,Monthly_Visits,Gender,Preferred_Product
0,56,26102,85,6,0,0
1,46,70336,75,18,1,3
2,32,105314,36,10,1,2
3,60,46641,99,5,0,1
4,25,54584,19,10,1,1
...,...,...,...,...,...,...
345,48,87641,37,12,0,3
346,52,56395,11,12,1,3
347,50,42700,77,19,1,0
348,38,54620,3,6,0,1
349,49,40559,33,2,1,0

In [13]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [14]:
kmeans=KMeans(n_clusters=3)
kmeans.fit(df)

C:\Users\choud\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

KMeans(n_clusters=3)

In [15]:
pred= kmeans.predict(df)
pred

array([1, 2, 0, 1, 2, 1, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1,
       0, 2, 1, 1, 2, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1,
       1, 0, 1, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 0, 2, 0, 1, 0, 0, 0, 1, 1,
       2, 0, 0, 2, 2, 2, 2, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 2, 1, 0, 0, 2, 0, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1,
       1, 1, 2, 0, 0, 2, 0, 1, 0, 0, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0,
       2, 2, 0, 0, 2, 2, 2, 1, 1, 0, 0, 0, 0, 2, 2, 1, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 2, 0, 1, 2, 0, 1, 0, 0, 0, 2, 0,
       0, 0, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 2, 2, 1, 1, 0,
       0, 2, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 1, 2, 2, 0, 0, 1, 2, 0, 2, 2,
       2, 0, 1, 1, 2, 2, 2, 1, 0, 2, 0, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 0, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 2,
       2, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 2, 1, 0, 0, 0, 2,
       1, 1, 2, 2, 2, 2, 0, 0, 1, 0, 0, 2, 1, 1, 1, 2, 1, 0, 0, 2, 2, 2,
       1, 0, 2, 0, 1, 2, 0, 1, 1, 2, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 2, 2,
       1, 1, 2, 2, 2, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 1],
      dtype=int32)

In [16]:
silhouette_score(df,labels=kmeans.labels_,metric='euclidean')

np.float64(0.5945464567691113)